"""
Configuration module for hospital SEIXHRD model simulations.

This module re-exports all configuration data from scenarios.py and provides
backward compatibility for existing imports. All data definitions are in scenarios.py.

Usage:
    from config import SCENARIO_COVID_DELTA
    from config_helpers import get_scenario_params
    params = get_scenario_params('covid_delta')
    results = simulate_master_hospital_model(**params)
"""

# Re-export everything from scenarios.py for backward compatibility
from scenarios import (
    # Core Parameters
    DEFAULT_SIM_PARAMS,
    DEFAULT_CAPACITY_PARAMS,
    AGE_POPS_DEFAULT,
    
    # Vaccine Parameters
    VACCINE_EFFICACY_PARAMS,
    VACCINATION_RATE_PARAMS,
    VACCINE_WANING_PARAMS,
    VACCINE_PROFILES,
    SIM_DURATION_PRESETS,
    
    # Transmission Presets
    TRANSMISSION_PRESETS,
    
    # Age Group Definitions
    AGE_LABELS,
    AGE_LABELS_SHORT,
    NUM_AGE_GROUPS,
    
    # Age-Specific Disease Parameters
    YOUNG_PARAMS_EMPIRICAL,
    MIDDLE_PARAMS_EMPIRICAL,
    ELDERLY_PARAMS_EMPIRICAL,
    AGE_PARAMS_EMPIRICAL,
    YOUNG_PARAMS_TEACHING,
    MIDDLE_PARAMS_TEACHING,
    ELDERLY_PARAMS_TEACHING,
    AGE_PARAMS_TEACHING,
    USE_EMPIRICAL_PARAMS,
    AGE_PARAMS_DEFAULT,
    YOUNG_PARAMS_ACTIVE,
    MIDDLE_PARAMS_ACTIVE,
    ELDERLY_PARAMS_ACTIVE,
    
    # Differential Mortality
    DIFFERENTIAL_MORTALITY_PARAMS,
    
    # Contact Matrices
    CONTACT_MATRIX_DEFAULT,
    CONTACT_MATRIX_HOMOGENEOUS,
    CONTACT_MATRIX_ASSORTATIVE,
    CONTACT_MATRIX_SCHOOL_CLOSURE,
    CONTACT_MATRIX_WORK_FROM_HOME,
    CONTACT_MATRIX_ELDERLY_SHIELDING,
    
    # Healthcare Systems
    HEALTHCARE_SYSTEM_SMALL,
    HEALTHCARE_SYSTEM_RURAL,
    HEALTHCARE_SYSTEM_SUBURBAN,
    HEALTHCARE_SYSTEM_URBAN,
    HEALTHCARE_SYSTEM_METROPOLITAN,
    HEALTHCARE_SYSTEM_WELL_RESOURCED,
    HEALTHCARE_SYSTEM_RESOURCE_LIMITED,
    HEALTHCARE_SYSTEM_SURGE_MILD,
    HEALTHCARE_SYSTEM_SURGE_MAJOR,
    
    # Initial Conditions
    DEFAULT_INITIAL_CONDITIONS,
    INITIAL_CONDITIONS_PRESETS,
    
    # Seasonal Parameters
    SEASONAL_PARAMS_NONE,
    SEASONAL_PARAMS_MILD,
    SEASONAL_PARAMS_MODERATE,
    SEASONAL_PARAMS_STRONG,
    
    # Waning Immunity
    WANING_NONE,
    WANING_SLOW,
    WANING_MODERATE,
    WANING_FAST,
    WANING_VERY_FAST,
    WANING_AGE_DIFFERENTIAL,
    
    # Demographic Parameters
    DEMOGRAPHIC_PARAMS_NONE,
    DEMOGRAPHIC_PARAMS_DEFAULT,
    DEMOGRAPHIC_PARAMS_HIGH_INCOME,
    DEMOGRAPHIC_PARAMS_LOW_INCOME,
    DEMOGRAPHIC_PARAMS_EQUILIBRIUM,
    DEMOGRAPHIC_PARAMS_NEONATAL_VAX,
    DEMOGRAPHIC_PRESETS,
    
    # Interventions
    INTERVENTION_NONE,
    INTERVENTION_EARLY_STRONG,
    INTERVENTION_EARLY_MODERATE,
    INTERVENTION_DELAYED_STRONG,
    INTERVENTION_DELAYED_MODERATE,
    INTERVENTION_TIERED_ESCALATING,
    INTERVENTION_TIERED_DEESCALATING,
    INTERVENTION_CYCLICAL,
    INTERVENTION_SUSTAINED_MODERATE,
    INTERVENTION_SHORT_SHARP,
    INTERVENTION_MULTI_WAVE,
    LOCKDOWN_SCENARIO,
    MULTIPLE_WAVES_SCENARIO,
    
    # Vaccination Strategies
    VACCINATION_STRATEGIES,
    VACCINE_EFFICACY_PRESETS,
    
    # Complete Scenarios
    SCENARIO_BASELINE,
    SCENARIO_LATE_ONSET_MILD_WAVE,
    SCENARIO_COVID_EARLY_2020,
    SCENARIO_COVID_DELTA,
    SCENARIO_COVID_OMICRON,
    SCENARIO_SEASONAL_FLU,
    SCENARIO_ENDEMIC_EQUILIBRIUM,
    SCENARIO_HOSPITAL_STRESS_TEST,
    SCENARIO_OPTIMAL_RESPONSE,
    SCENARIO_RESOURCE_LIMITED,
    SCENARIO_SCHOOL_OUTBREAK,
    SCENARIO_CARE_HOME_OUTBREAK,
    SCENARIO_SURGE_CAPACITY,
    SCENARIO_CYCLICAL_POLICY,
    SCENARIO_NOVEL_PATHOGEN,
    SCENARIO_VACCINE_ROLLOUT_PHASED,
    SCENARIO_VARIANT_EMERGENCE,
    SCENARIO_CAPACITY_COLLAPSE,
    SCENARIO_ENDEMIC_VACCINATION,
    SCENARIO_SCHOOL_REOPENING,
    SCENARIO_SENSITIVITY_TRANSMISSION,
    SCENARIO_SENSITIVITY_CAPACITY,
    SCENARIO_POPULATION_DYNAMICS,
    SCENARIO_NEONATAL_VACCINATION,
    SCENARIO_REGISTRY,
    
    # Sensitivity Analysis
    PARAMETER_RANGES,
)

# Re-export type definitions for convenience
from model_types import (
    SimParams,
    CapacityParams,
    AgeParams,
    ContactMatrix,
    VaccineEfficacyParams,
    VaccineWaningParams,
    SeasonalParams,
    Intervention,
    DemographicParams,
    DifferentialMortalityParams
)
